# Generated by Django 5.2.6 on 2025-10-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_salalounge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periquera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periquera',
                'verbose_name_plural': 'Periqueras',
            },
        ),
        migrations.AlterModelOptions(
            name='salalounge',
            options={'verbose_name': 'Sala-Lounge', 'verbose_name_plural': 'Salas-Lounge'},
        ),
    ]
