# Generated by Django 5.2.6 on 2025-10-07 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0014_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('responsable', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Por iniciar', 'Por iniciar'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Por iniciar', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.tipoevento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoMobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiliario_asignado', to='inventory.evento')),
            ],
        ),
    ]
