# Generated by Django 5.2.6 on 2025-10-14 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpa',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='carpa',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cristaleria',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='cristaleria',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cubierto',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='cubierto',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extra',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='extra',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loza',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='loza',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manteleria',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='manteleria',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesa',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='periquera',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='periquera',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pistatarima',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='pistatarima',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salalounge',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='salalounge',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='silla',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='inventory.bodega'),
        ),
        migrations.AddField(
            model_name='silla',
            name='cantidad_en_mantenimiento',
            field=models.IntegerField(default=0),
        ),
    ]
