# Generated by Django 5.2.6 on 2025-09-23 21:32

from django.db import migrations

def assign_admin_role(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('posts', 'Profile')
    for user in User.objects.all():
        # Usamos get_or_create para evitar errores si el perfil ya existe por alguna razón
        Profile.objects.get_or_create(user=user, defaults={'rol': 'Admin'})

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(assign_admin_role),
    ]
