# Generated by Django 5.2.6 on 2025-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_assign_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('Encargado', 'Encargado'), ('Proveedor', 'Proveedor')], default='Encargado', max_length=10),
        ),
    ]
